import { GameProfile } from '../types/vpn';

export const GAME_PROFILES: GameProfile[] = [
  {
    id: 'codm',
    gameTitle: 'Call of Duty: Mobile',
    packageName: 'com.activision.callofduty.shooter',
    icon: 'flame',
    genre: 'FPS / Battle Royale',
    ports: [7500, 7501, 7502, 8000, 10000],
    recommendedMtu: 1360,
    dscpTag: 0x2E, // Expedited Forwarding (EF)
    defaultServerId: 'tokyo-jp1',
    protocol: 'UDP_FAST_TRACK',
    description: 'High-tick rate UDP packet acceleration with anti-fragmentation MTU tuning.',
  },
  {
    id: 'pubgm',
    gameTitle: 'PUBG Mobile',
    packageName: 'com.tencent.ig',
    icon: 'shield-checkmark',
    genre: 'Battle Royale',
    ports: [10012, 10013, 10014, 17500],
    recommendedMtu: 1380,
    dscpTag: 0x2E,
    defaultServerId: 'singapore-sg1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Bypasses cellular carrier throttling on battle arena UDP relay nodes.',
  },
  {
    id: 'wildrift',
    gameTitle: 'League of Legends: Wild Rift',
    packageName: 'com.riotgames.league.wildrift',
    icon: 'flash',
    genre: 'MOBA',
    ports: [5000, 5001, 5100, 5200],
    recommendedMtu: 1350,
    dscpTag: 0x2E,
    defaultServerId: 'frankfurt-de1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Zero input-lag packet pacing for skill-shot registration & latency stability.',
  },
  {
    id: 'genshin',
    gameTitle: 'Genshin Impact',
    packageName: 'com.miHoYo.GenshinImpact',
    icon: 'planet',
    genre: 'Action RPG',
    ports: [8888, 8889, 443],
    recommendedMtu: 1400,
    dscpTag: 0x28, // CS5
    defaultServerId: 'virginia-us1',
    protocol: 'HYBRID_TCP_UDP',
    description: 'Hybrid TCP/UDP tunnel ensuring uninterrupted co-op multiplayer sync.',
  },
  {
    id: 'valorantm',
    gameTitle: 'Valorant Mobile',
    packageName: 'com.riotgames.valorant.mobile',
    icon: 'crosshair',
    genre: 'Tactical Shooter',
    ports: [7000, 7001, 7100, 8500],
    recommendedMtu: 1380,
    dscpTag: 0x2E,
    defaultServerId: 'oregon-us2',
    protocol: 'UDP_FAST_TRACK',
    description: '128-tick server routing with DSCP 46 priority and Wi-Fi Low Latency Lock.',
  },
  {
    id: 'mlbb',
    gameTitle: 'Mobile Legends: Bang Bang',
    packageName: 'com.mobile.legends',
    icon: 'sword',
    genre: 'MOBA',
    ports: [30000, 30001, 30002],
    recommendedMtu: 1370,
    dscpTag: 0x2E,
    defaultServerId: 'singapore-sg1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Anti-jitter buffer prevents micro-freezes during critical 5v5 teamfights.',
  },
  {
    id: 'freefire',
    gameTitle: 'Free Fire MAX',
    packageName: 'com.dts.freefiremax',
    icon: 'bonfire',
    genre: 'Battle Royale',
    ports: [9000, 9050, 9100],
    recommendedMtu: 1360,
    dscpTag: 0x2E,
    defaultServerId: 'saopaulo-br1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Bypasses standard telecom routing bottlenecks to direct gaming POPs.',
  },
  {
    id: 'brawlstars',
    gameTitle: 'Brawl Stars',
    packageName: 'com.supercell.brawlstars',
    icon: 'skull',
    genre: 'Action Brawler',
    ports: [9339],
    recommendedMtu: 1400,
    dscpTag: 0x2E,
    defaultServerId: 'frankfurt-de1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Direct UDP connection to Supercell edge clusters with sub-1ms jitter.',
  },
  {
    id: 'custom',
    gameTitle: 'Custom Target Game',
    packageName: 'com.example.customgame',
    icon: 'game-controller',
    genre: 'Custom Esports Title',
    ports: [7000, 8000, 9000, 10000],
    recommendedMtu: 1380,
    dscpTag: 0x2E,
    defaultServerId: 'tokyo-jp1',
    protocol: 'UDP_FAST_TRACK',
    description: 'Customizable target package name, port range, and routing parameters.',
  },
];
