import { GamingServerNode } from '../types/vpn';

export const GAMING_SERVERS: GamingServerNode[] = [
  {
    id: 'tokyo-jp1',
    name: 'Tokyo JP01',
    region: 'Asia-Pacific East',
    country: 'Japan',
    flag: '🇯🇵',
    host: 'tokyo-jp1.gaming.realgamevpn.net',
    port: 7500,
    basePingMs: 18,
    currentPingMs: 19,
    loadPercent: 42,
    reliability: 99.98,
    coordinates: { x: 78, y: 35 },
  },
  {
    id: 'singapore-sg1',
    name: 'Singapore SG01',
    region: 'Southeast Asia Core',
    country: 'Singapore',
    flag: '🇸🇬',
    host: 'singapore-sg1.gaming.realgamevpn.net',
    port: 10012,
    basePingMs: 15,
    currentPingMs: 16,
    loadPercent: 55,
    reliability: 99.99,
    coordinates: { x: 70, y: 52 },
  },
  {
    id: 'frankfurt-de1',
    name: 'Frankfurt DE01',
    region: 'Europe Central Core',
    country: 'Germany',
    flag: '🇩🇪',
    host: 'frankfurt-de1.gaming.realgamevpn.net',
    port: 5000,
    basePingMs: 24,
    currentPingMs: 25,
    loadPercent: 38,
    reliability: 99.95,
    coordinates: { x: 48, y: 28 },
  },
  {
    id: 'london-uk1',
    name: 'London UK01',
    region: 'Europe West Core',
    country: 'United Kingdom',
    flag: '🇬🇧',
    host: 'london-uk1.gaming.realgamevpn.net',
    port: 5000,
    basePingMs: 27,
    currentPingMs: 28,
    loadPercent: 47,
    reliability: 99.94,
    coordinates: { x: 44, y: 26 },
  },
  {
    id: 'virginia-us1',
    name: 'N. Virginia US01',
    region: 'US East Gaming Hub',
    country: 'United States',
    flag: '🇺🇸',
    host: 'va-us1.gaming.realgamevpn.net',
    port: 8888,
    basePingMs: 21,
    currentPingMs: 22,
    loadPercent: 62,
    reliability: 99.99,
    coordinates: { x: 26, y: 34 },
  },
  {
    id: 'oregon-us2',
    name: 'Oregon US02',
    region: 'US West Gaming Hub',
    country: 'United States',
    flag: '🇺🇸',
    host: 'oregon-us2.gaming.realgamevpn.net',
    port: 7000,
    basePingMs: 23,
    currentPingMs: 24,
    loadPercent: 49,
    reliability: 99.97,
    coordinates: { x: 18, y: 30 },
  },
  {
    id: 'saopaulo-br1',
    name: 'São Paulo BR01',
    region: 'South America Core',
    country: 'Brazil',
    flag: '🇧🇷',
    host: 'saopaulo-br1.gaming.realgamevpn.net',
    port: 9339,
    basePingMs: 31,
    currentPingMs: 33,
    loadPercent: 34,
    reliability: 99.91,
    coordinates: { x: 33, y: 68 },
  },
  {
    id: 'sydney-au1',
    name: 'Sydney AU01',
    region: 'Oceania East Core',
    country: 'Australia',
    flag: '🇦🇺',
    host: 'sydney-au1.gaming.realgamevpn.net',
    port: 7500,
    basePingMs: 29,
    currentPingMs: 30,
    loadPercent: 41,
    reliability: 99.96,
    coordinates: { x: 86, y: 72 },
  },
];
